apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcs-server-dep
  namespace: hcs-%{ENVIRONMENT}-ns
  labels:
    app: hcs-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcs-server-app
  template:
    metadata:
      name: hcs-server-pod
      labels:
        app: hcs-server-app
    spec:
      containers:
        - name: hcs-server-co
          image: ${IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
