apiVersion: v1
kind: Service
metadata:
  name: hcs-server-svc
  namespace: hcs-${ENVIRONMENT}-ns
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hcs-server-app
